# Generated by Django 2.0.5 on 2018-09-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatstatistics',
            name='Publicity',
            field=models.BooleanField(default=True),
        ),
    ]
