# Generated by Django 2.0.5 on 2018-09-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20180911_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatstats',
            name='Publicity',
            field=models.BooleanField(default=True),
        ),
    ]
