# Generated by Django 2.0.5 on 2018-09-13 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatstats_publicity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sender', models.CharField(max_length=50)),
                ('Receiver', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=250)),
                ('Time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
