# Generated by Django 2.0.5 on 2018-09-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='useremail',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(upload_to='profile'),
        ),
    ]
