# Generated by Django 2.0.5 on 2018-09-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20180914_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='useremail',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(upload_to='Profile/'),
        ),
    ]
