# Generated by Django 2.0.5 on 2018-09-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20180914_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(upload_to=''),
        ),
    ]
